// Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

// 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

// By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.

const target = 4000000;

const fibbonachi = [1, 2];

const fibbo = () => {
  let totalSum = 0;

  for (let i = 0; fibbonachi[i] < target; i++) {
    let meme = fibbonachi[i] + fibbonachi[i + 1];
    fibbonachi.push(meme);
  }

  fibbonachi.forEach((e) => {
    if (e % 2 === 0) {
      return (totalSum += e);
    }
  });

  return totalSum;
};



console.log(fibbo());
